#ifndef _C_BRICK_GAME_V1_BRICK_GAME_TETRIS_COLORS_H
#define _C_BRICK_GAME_V1_BRICK_GAME_TETRIS_COLORS_H

#include <ncurses.h>

#define COLOR_BLOCK_STICK COLOR_RED
#define COLOR_BLOCK_L_SHAPE 202
#define COLOR_BLOCK_REV_L_SHAPE 11
#define COLOR_BLOCK_SQUARE 212
#define COLOR_BLOCK_Z_SHAPE 55
#define COLOR_BLOCK_REV_Z_SHAPE 40
#define COLOR_BLOCK_T_SHAPE COLOR_BLUE
#define COLOR_EMPTY COLOR_BLACK

#endif